# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c328e4f3405fc6e119fe644c7761d616ab10ac36071ef5bf655eba5de15f5db51fc8e05a38a49a079313a262e543cb5ab4eea8038353444dd3fda318f357a28

test:
  secret_key_base: 601cafde3c40231338e048c128f588a24646c0869fd6a98a64882adf7c5682760e707204df67ba683506a45e6ac62248a31a6ba984dc54fe70b455f120a35476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
